import { BrainCircuit } from "lucide-react";
import FeaturePageLayout from "./FeaturePageLayout";

const AIRecommendations = () => (
  <FeaturePageLayout
    icon={BrainCircuit}
    title="AI-Powered Recommendations"
    description="A state-of-the-art AI system generates detailed reports, analysis, and timely notifications so you never miss important health updates."
    currentPath="/features/ai-recommendations"
    keyPoints={[
      { title: "AI-Generated Reports", description: "Receive detailed health reports generated by AI based on your logged symptoms and cycle data." },
      { title: "Health Analysis", description: "Get meaningful analysis of your health patterns to better understand your body over time." },
      { title: "Timely Notifications", description: "Never miss your period or a health update with smart, well-timed notifications." },
      { title: "Personalized Insights", description: "Recommendations are tailored to your unique health profile and history." },
    ]}
  />
);

export default AIRecommendations;
